baseURL = 'https://sinclairhuang.org/'
languageCode = 'en-us'
title = 'Sinclair Huang - Research & Consulting'
theme = 'PaperMod'
publishDir = "docs"

[params]
author = 'Po-Sung (Sinclair) Huang'
description = 'Independent researcher and executive advisor'

[params.homeInfoParams]
Title = "Po-Sung (Sinclair) Huang"
Content = "Independent research and executive advisory on AI-driven industrial competitiveness.\n\nPhD (EDBA, HEC Li√®ge) | Taiwan"

[params.profileMode]
enabled = false

[[menu.main]]
name = 'Home'
url = '/'
weight = 1

[[menu.main]]
name = 'Publications'
url = '/publications/'
weight = 2

[[menu.main]]
name = 'Projects'
url = '/projects/'
weight = 3

[[menu.main]]
name = 'Blog'
url = '/blog/'
weight = 4

[[menu.main]]
name = 'About'
url = '/about/'
weight = 5

[[menu.main]]
name = 'News'
url = '/news/'
weight = 6

[markup.goldmark.renderer]
unsafe = true
