baseURL = "https://sinclairhuang.org/"
languageCode = "en-us"
title = "Sinclair Huang"
theme = "PaperMod"

[params]
    env = "production"
    title = "Sinclair Huang, PhD (EDBA)"
    description = "Researching AI-Driven Industrial Competitiveness & Capital Markets"
    
    [params.homeInfoParams]
        Title = "Sinclair Huang, PhD (EDBA)"
        Content = "Independent Researcher | Special Advisor at Continental Carbon. Focusing on AI, Semiconductors, and Biotech Infrastructure. [2026.02.18 Updated]"

[menu]
  [[menu.main]]
    name = "Publications"
    url = "/publications"
    weight = 10
  [[menu.main]]
    name = "Research Profile"
    url = "/about"
    weight = 20
