baseURL = 'https://sinclairhuang.org/'
languageCode = 'en-us'
title = 'Sinclair Huang - Research & Consulting'
theme = 'PaperMod'
publishDir = "docs"

[params]
author = 'Po-Sung (Sinclair) Huang'
description = 'Independent researcher and executive advisor'

[params.homeInfoParams]
Title = "Po-Sung (Sinclair) Huang"
Content = "Independent research and executive advisory on AI-driven industrial competitiveness.\n\nPhD (EDBA, HEC Li√®ge) | Taiwan"

[params.profileMode]
enabled = false







[markup.goldmark.renderer]
unsafe = true



[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Publications"
    url = "/publications"
    weight = 20
  [[menu.main]]
    name = "Data"
    url = "/data"
    weight = 30
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 40
